### ISSUE TITLE
Integration in fmt (basically c++20 std::format)

### ISSUE THREAD

**Issue by SanderBouwhuis** [erthink/erthink#1]
Is there any chance you could submit your double-to-ascii magic to the fmt library?
In this topic https://github.com/fmtlib/fmt/issues/1426 you mention your implementation is a lot (maybe 3x) faster than the current implementation.

1. I don't dare submit it because I'm afraid I might screw up things.
2. Is it even 'legal' to make use of your double-to-ascii code in the fmt library?

**Comment by erthink** [comment]
@SanderBouwhuis, there are four main scenarios for using the double-to-string conversion:
1. given precision with rounding, e.g. `0.12345e789`.
2. given length with rounding (i.e. to choice useful format while number of chars is fixed).
3. to produce a shortest string representation which roundtrip-convertible to an original double value, e.g. for serialization to JSON.
4. to produce a long decimal representations with the given error value.

Historically and for now, my implementation supports third case only. For support other cases a significant changes/improvements are required. I do this as I have free time, but this job is not done...

In addition, it is not obvious that such improvements are really needed in `{fmt}` and will pass the review since significantly increase the volume and complexity of the code. For instance, support for 80-bit and 128-bit IEEE-754 formats requires 128-bit integer arithmetic and so on.

@vitaut, FYI.

**Comment by SanderBouwhuis** [comment]
Aha, ok. That makes things clear.
I'm glad I didn't try this myself then.

All things said though, you did some very impressive optimizations. I assume you are using the Ryu implementation as a basis? Or is this Grisu-3?

**Comment by erthink** [comment]
>  I assume you are using the Ryu implementation as a basis? Or is this Grisu-3?

Take look to [#1](https://github.com/erthink/erthink/blob/5c345bbb73a3dd23b7c30fab266f09dabdefec1a/erthink_d2a.h#L20-L31), [#2](https://github.com/erthink/dtoa-benchmark#preamble).

**Comment by SanderBouwhuis** [comment]
Thanks, I hadn't seen that part.
Good luck with trying to make the conversion complete!
